apiVersion: v1
kind: Service
metadata:
  name: openedge-etcd-external
  labels:
    app: etcd
    etcd_cluster: openedge-etcd-cluster
spec:
  selector:
    app: etcd
    etcd_cluster: openedge-etcd-cluster
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
      nodePort: 32379
  type: NodePort
